# Generated by Django 4.2.7 on 2024-01-10 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FootBall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matches', models.IntegerField()),
                ('goals', models.IntegerField()),
                ('age', models.IntegerField()),
                ('name', models.CharField(max_length=20)),
                ('fastest_goal', models.IntegerField()),
            ],
        ),
    ]
